# Generated by Django 5.0.2 on 2024-02-07 10:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_carimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_at_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Final sale price of the car.",
                        max_digits=10,
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="carimage",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="reviewer",
        ),
        migrations.AddField(
            model_name="car",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(
                default=0, help_text="Mileage of the car in kilometers"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="car",
            name="sold_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[("AV", "Available"), ("RV", "Reserved"), ("SD", "Sold")],
                default="AV",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="vin",
            field=models.CharField(
                default=0,
                help_text="Vehicle Identification Number",
                max_length=17,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="A brief description of the image.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="carimage",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which the image will appear in a carousel.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Biography"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="User rating based on transaction history",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                help_text="Rating on a scale from 1 to 10.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("car", "reviewer"), name="unique_review_per_user_per_car"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.car"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.car"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "car")},
        ),
    ]
