# Generated by Django 5.0.2 on 2024-02-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_message_purchase_wishlist_alter_carimage_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="category",
        ),
        migrations.AddField(
            model_name="car",
            name="categories",
            field=models.ManyToManyField(to="listings.category"),
        ),
    ]
