# Generated by Django 5.0.2 on 2024-03-05 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_remove_car_category_car_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(default="Sedan", max_length=100, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FuelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="Gas", max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="car",
            name="categories",
        ),
        migrations.AddField(
            model_name="car",
            name="body_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.bodytype",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.carmodel"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="listings.fueltype",
            ),
        ),
        migrations.AddField(
            model_name="carmodel",
            name="make",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="listings.make",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="make",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="listings.make"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AlterUniqueTogether(
            name="carmodel",
            unique_together={("make", "name")},
        ),
    ]
