# Generated by Django 5.0.2 on 2024-04-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[("AV", "Available"), ("RV", "Reserved"), ("SD", "Sold")],
                default="AV",
                max_length=15,
            ),
        ),
    ]
