# Generated by Django 5.0.2 on 2024-04-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_alter_car_year_alter_review_reviewer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="year",
            field=models.PositiveIntegerField(),
        ),
    ]
